import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'

async function completeOnboarding(page: Page, days = '3') {
  await page.goto('/')
  await expect(page).toHaveURL(/\/onboarding$/)
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByRole('button', { name: days === '2' ? '2 days' : '3 days' }).click()
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByRole('button', { name: 'Flexible' }).click()
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByLabel(/I have this set/i).check()
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByLabel(/no relevant medical restriction/i).check()
  await page.getByRole('button', { name: /continue/i }).click()
  await page.getByTestId('onboarding-finish').click()
  await expect(page).toHaveURL(/\/today$/)
}

async function saveOneSetAndAdvance(page: Page, value = '8') {
  await page.getByTestId('set-reps').fill(value)
  await page.getByTestId('set-complete').click()
  await expect(page.getByText(/set 2 of/i)).toBeVisible()
  await page.getByTestId('set-reps').fill(value)
  await page.getByTestId('set-complete').click()
}

async function finishWorkoutWithOneSet(page: Page) {
  await page.getByTestId('start-workout').click()
  await page.getByRole('button', { name: /start working sets/i }).click()
  await expect(page.getByTestId('active-exercise')).toBeVisible()
  for (let index = 0; index < 12; index += 1) {
    const reps = page.getByTestId('set-reps')
    const duration = page.getByTestId('set-duration')
    if (await reps.isVisible()) await reps.fill('8')
    else await duration.fill('15')
    await page.getByTestId('set-complete').click()
    const next = page.getByRole('button', { name: /next exercise/i })
    if (await next.isVisible()) await next.click()
    else break
  }
  await page.getByTestId('finish-workout').click()
  await expect(page.getByRole('heading', { name: /cool down/i })).toBeVisible()
  await page.getByRole('button', { name: 'Finish workout', exact: true }).click()
  await page.getByTestId('finish-confirm').click()
  await expect(page).toHaveURL(/\/history$/)
}

async function uploadBackupFromMemory(page: Page, backup: Buffer) {
  await page.getByTestId('backup-file-input').evaluate((input, encoded) => {
    const bytes = Uint8Array.from(atob(encoded), (character) => character.charCodeAt(0))
    const transfer = new DataTransfer()
    transfer.items.add(new File([bytes], 'training-tracker-backup.json', { type: 'application/json' }))
    ;(input as HTMLInputElement).files = transfer.files
    input.dispatchEvent(new Event('change', { bubbles: true }))
  }, backup.toString('base64'))
}

test.describe('Training Tracker P0 smoke flows', () => {
  test('starts onboarding and exposes safety and install guidance', async ({ page }) => {
    await page.goto('/')
    await expect(page).toHaveURL(/\/onboarding$/)
    await expect(page.getByRole('heading', { name: /build your training rhythm/i })).toBeVisible()
    await expect(page.getByText(/Safari.*Share.*Add to Home Screen/i)).toBeVisible()
    await page.getByRole('button', { name: /continue/i }).click()
    await page.getByRole('button', { name: /continue/i }).click()
    await page.getByRole('button', { name: /continue/i }).click()
    await page.getByLabel(/I have this set/i).check()
    await page.getByRole('button', { name: /continue/i }).click()
    await page.getByLabel(/no relevant medical restriction/i).check()
    await page.getByRole('button', { name: /continue/i }).click()
    await expect(page.getByText(/backup after your first completed workout/i)).toBeVisible()
  })

  test('has responsive mobile navigation, keyboard focus, and no serious axe violations @a11y', async ({ page }) => {
    const consoleErrors: string[] = []
    page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
    page.on('pageerror', (error) => consoleErrors.push(error.message))
    await page.goto('/')
    await expect(page.getByRole('navigation', { name: /primary navigation/i })).toBeVisible()
    await expect(page.locator('main')).toBeVisible()
    for (const width of [320, 390]) {
      await page.setViewportSize({ width, height: 700 })
      const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
      expect(horizontalOverflow).toBe(false)
      const skipLink = page.getByRole('link', { name: 'Skip to content' })
      await skipLink.focus()
      await expect(skipLink).toBeFocused()
      await page.keyboard.press('Enter')
      await expect(page.locator('main')).toBeFocused()
      const results = await new AxeBuilder({ page }).analyze()
      expect(results.violations.filter((violation) => violation.impact === 'critical' || violation.impact === 'serious')).toEqual([])
    }
    expect(consoleErrors).toEqual([])
  })

  test('offline startup serves the cached local shell @chromium-only', async ({ page, context }) => {
    await page.goto('/')
    await page.evaluate(async () => { await navigator.serviceWorker.ready })
    await page.reload()
    expect(await page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
    await context.setOffline(true)
    await page.reload({ waitUntil: 'domcontentloaded' })
    await expect(page.getByRole('main')).toBeVisible()
    await expect(page).toHaveTitle(/Training Tracker/)
    expect(await page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  })

  test('offers the optional desk reset without creating progression history', async ({ page }) => {
    await completeOnboarding(page)
    await page.getByRole('link', { name: /five-minute desk reset/i }).click()
    await expect(page.getByRole('heading', { name: /five-minute desk reset/i })).toBeVisible()
    await expect(page.getByTestId('desk-reset-timer')).toHaveText('5:00')
    await page.getByRole('button', { name: /next movement/i }).click()
    await expect(page.getByTestId('desk-reset-timer')).toHaveText('4:00')
    await page.getByRole('link', { name: 'History' }).click()
    await expect(page.getByText(/no completed workouts yet/i)).toBeVisible()
  })

  test('production manifest and service worker are present', async ({ page, request }) => {
    const manifest = await request.get('/manifest.webmanifest')
    expect(manifest.ok()).toBe(true)
    const manifestJson = await manifest.json()
    expect(manifestJson.display).toBe('standalone')
    expect(manifestJson.start_url).toBe('/')
    expect(manifestJson.icons.length).toBeGreaterThanOrEqual(2)
    const worker = await request.get('/sw.js')
    expect(worker.ok()).toBe(true)
    expect(await worker.text()).toContain('SKIP_WAITING')
    await page.goto('/')
    await expect(page).toHaveTitle(/Training Tracker/)
  })

  test('onboarding draft survives refresh and validates timezone and fixed weekdays', async ({ page }) => {
    await page.goto('/onboarding')
    await page.getByLabel('Timezone').fill('America/Toronto')
    await page.getByRole('button', { name: /continue/i }).click()
    await page.reload()
    await expect(page.getByLabel('Timezone')).toHaveValue('America/Toronto')
    await page.getByRole('button', { name: /continue/i }).click()
    await page.getByRole('button', { name: '3 days' }).click()
    await page.getByRole('button', { name: /continue/i }).click()
    await page.getByRole('button', { name: 'Fixed weekdays' }).click()
    await page.getByLabel('Monday').uncheck()
    await page.getByRole('button', { name: /continue/i }).click()
    await expect(page.getByRole('alert')).toContainText(/exactly 3 weekdays/i)
    await page.getByLabel('Monday').check()
    await page.getByLabel('Wednesday').check()
    await page.getByLabel('Friday').check()
    await page.getByRole('button', { name: /continue/i }).click()
    await expect(page.getByText(/confirm your band set/i)).toBeVisible()
  })

  test('accessible destructive dialogs trap focus and return it', async ({ page }) => {
    await page.goto('/onboarding')
    await expect(page.locator('main')).toBeVisible()
    await page.getByRole('link', { name: 'Settings' }).click()
    await page.locator('a[href="/settings/reset"]').click()
    const trigger = page.getByTestId('reset-local-data')
    await trigger.focus()
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: /reset all local data/i })
    await expect(dialog).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(dialog).toBeHidden()
    await expect(trigger).toBeFocused()
  })

  test('exercise guides keep written content offline and load safe videos only on click', async ({ page, context }) => {
    await page.goto('/exercises')
    await page.getByTestId('exercise-card-lower-front-squat-band').click()
    await expect(page.getByTestId('exercise-guide')).toContainText(/breathing and tempo/i)
    await expect(page.getByRole('link', { name: /open on youtube/i })).toBeVisible()
    await expect(page.locator('iframe')).toHaveCount(0)
    await page.getByRole('button', { name: /load .* demonstration video/i }).click()
    await expect(page.locator('iframe')).toHaveAttribute('src', /youtube-nocookie\.com\/embed/)
    await context.setOffline(true)
    await expect(page.getByTestId('exercise-guide')).toContainText(/written guide remains available/i)
  })

  test('update notice defers during a workout and offers activation outside it', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByTestId('app-shell')).toBeVisible()
    await page.evaluate(() => window.dispatchEvent(new Event('training-tracker:update-ready')))
    await expect(page.getByTestId('update-status')).toContainText(/new version is ready/i)
    await page.getByRole('button', { name: 'Later' }).click()
    await expect(page.getByTestId('update-status')).toBeHidden()
  })

  test('active workout update notice cannot activate or reload the page', async ({ page }) => {
    await completeOnboarding(page)
    await page.getByTestId('start-workout').click()
    await expect(page.getByRole('heading', { name: /prepare to move/i })).toBeVisible()
    await expect(page.getByLabel(/four-minute warm-up/i).locator('article')).toHaveCount(4)
    await expect(page.getByText('4:00')).toBeVisible()
    await page.getByRole('button', { name: /start working sets/i }).click()
    await expect(page.getByTestId('movement-preview')).toBeVisible()
    await expect(page.getByRole('img', { name: /setup illustration/i })).toBeVisible()
    await expect(page.getByRole('button', { name: /load .* demonstration video/i })).toBeVisible()
    await page.setViewportSize({ width: 390, height: 844 })
    const fold = await page.evaluate(() => {
      const bottom = (selector: string) => Math.round(document.querySelector(selector)?.getBoundingClientRect().bottom ?? Number.POSITIVE_INFINITY)
      const navTop = Math.round(document.querySelector('.bottom-nav')?.getBoundingClientRect().top ?? 0)
      return { navTop, current: bottom('[data-testid="active-exercise"]'), previous: bottom('[data-testid="previous-result"]'), bands: bottom('.set-entry-card fieldset'), save: bottom('[data-testid="set-complete"]') }
    })
    expect(fold.current).toBeLessThan(fold.navTop)
    expect(fold.previous).toBeLessThan(fold.navTop)
    expect(fold.bands).toBeLessThan(fold.navTop)
    expect(fold.save).toBeLessThan(fold.navTop)
    const reloads: string[] = []
    page.on('framenavigated', (frame) => { if (frame === page.mainFrame()) reloads.push(frame.url()) })
    await page.evaluate(() => window.dispatchEvent(new Event('training-tracker:update-ready')))
    await expect(page.getByTestId('update-status')).toContainText(/finish or pause/i)
    await expect(page.getByRole('button', { name: /update now/i })).toHaveCount(0)
    await page.waitForTimeout(100)
    expect(reloads).toEqual([])
    await expect(page.getByTestId('active-exercise')).toBeVisible()
  })

  test('starts, refreshes, resumes, finishes, and shows exercise-level history plus recommendation', async ({ page }) => {
    await completeOnboarding(page)
    await page.getByTestId('start-workout').click()
    await page.getByRole('button', { name: /start working sets/i }).click()
    await expect(page.getByTestId('active-exercise')).toBeVisible()
    await saveOneSetAndAdvance(page)
    await page.locator('.workout-top').getByRole('button', { name: 'Pause', exact: true }).click()
    await page.getByRole('button', { name: /pause and save/i }).click()
    await expect(page).toHaveURL(/\/today$/)
    await page.getByTestId('resume-workout').click()
    await page.reload()
    const restartWarmup = page.getByRole('button', { name: /start working sets/i })
    if (await restartWarmup.isVisible()) await restartWarmup.click()
    await expect(page.getByTestId('active-exercise')).toBeVisible()
    await page.getByRole('button', { name: /next exercise/i }).click()
    for (let index = 0; index < 12; index += 1) {
      await saveOneSetAndAdvance(page)
      const next = page.getByRole('button', { name: /next exercise/i })
      if (await next.isVisible()) await next.click()
      else break
    }
    await page.getByTestId('finish-workout').click()
    await expect(page.getByRole('heading', { name: /cool down/i })).toBeVisible()
    await page.getByRole('button', { name: 'Finish workout', exact: true }).click()
    await page.getByTestId('finish-confirm').click()
    await expect(page).toHaveURL(/\/history$/)
    await expect(page.getByTestId(/history-session-/).first()).toBeVisible()
    await page.getByTestId(/history-session-/).first().click()
    await expect(page.getByText(/previous result|no previous result/i).first()).toBeVisible()
    await page.getByRole('link', { name: /today/i }).click()
    await finishWorkoutWithOneSet(page)
    await page.getByRole('link', { name: /today/i }).click()
    await finishWorkoutWithOneSet(page)
    await page.getByRole('link', { name: /today/i }).click()
    await page.getByTestId('start-workout').click()
    await page.getByRole('button', { name: /start working sets/i }).click()
    await expect(page.getByText(/proposed target:/i)).toBeVisible()
    await page.getByText(/proposed target:/i).click()
    await expect(page.getByTestId('confirm-recommendation')).toBeVisible()
  })

  test('switches two/three-day schedules, validates fixed weekdays, and restores a substitution', async ({ page }) => {
    await completeOnboarding(page, '2')
    await page.getByRole('link', { name: 'Settings' }).click()
    await page.getByRole('link', { name: /schedule/i }).click()
    await page.getByRole('button', { name: '3 days' }).click()
    await page.getByRole('button', { name: 'Fixed' }).click()
    await page.getByLabel('Mon').check()
    await page.getByLabel('Wed').check()
    await page.getByLabel('Fri').check()
    await page.getByLabel('Fri').uncheck()
    await page.getByRole('button', { name: /save schedule/i }).click()
    await expect(page.getByRole('alert').first()).toContainText(/exactly 3 weekdays/i)
    await page.getByLabel('Fri').check()
    await page.getByRole('button', { name: /save schedule/i }).click()
    await expect(page.getByText(/schedule saved/i)).toBeVisible()
    await page.getByRole('link', { name: /settings/i }).first().click()
    await page.getByRole('link', { name: /substitutions/i }).click()
    const select = page.getByTestId('substitution-select').first()
    await select.selectOption({ index: 1 })
    await expect(page.getByText(/substitution saved/i)).toBeVisible()
    await page.getByTestId('restore-substitution').first().click()
    await expect(page.getByText(/default exercise restored/i)).toBeVisible()
  })

  test('backup preview rejects malformed and checksum-invalid files and reset requires confirmation', async ({ page }) => {
    await completeOnboarding(page)
    await page.getByRole('link', { name: 'Settings' }).click()
    await page.getByRole('link', { name: /backups/i }).click()
    await page.getByTestId('backup-file-input').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":1}') })
    await expect(page.getByTestId('backup-error')).toContainText(/backup|validation|malformed/i)
    const checksumInvalid = { schemaVersion: 1, appVersion: '0.1.0', exportedAt: new Date().toISOString(), bands: [], substitutions: [], sessions: [], exerciseLogs: [], setLogs: [], checksum: { algorithm: 'SHA-256', value: '0'.repeat(64) } }
    await page.getByTestId('backup-file-input').setInputFiles({ name: 'checksum.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(checksumInvalid)) })
    await expect(page.getByTestId('backup-error')).toContainText(/checksum/i)
    await page.getByRole('link', { name: /settings/i }).first().click()
    await page.locator('a[href="/settings/reset"]').click()
    await page.getByTestId('reset-local-data').click()
    await expect(page.getByRole('dialog', { name: /reset all local data/i })).toBeVisible()
    await page.getByTestId('reset-cancel').click()
    await expect(page.getByTestId('reset-local-data')).toBeVisible()
  })

  test('exports a real backup, resets, restores by Merge and Replace, and preserves history', async ({ page }) => {
    await page.addInitScript(() => { Object.defineProperty(Navigator.prototype, 'share', { configurable: true, value: undefined }); Object.defineProperty(Navigator.prototype, 'canShare', { configurable: true, value: undefined }) })
    await completeOnboarding(page)
    await finishWorkoutWithOneSet(page)
    const historyBefore = (await page.getByTestId('history-list').innerText()).trim()
    await page.getByRole('link', { name: 'Settings' }).click()
    await page.getByRole('link', { name: /backups/i }).click()
    const downloadPromise = page.waitForEvent('download')
    await page.getByTestId('backup-export').click()
    const download = await downloadPromise
    const backupPath = await download.path()
    expect(backupPath).toBeTruthy()
    const backup = await readFile(backupPath as string)
    expect(JSON.parse(backup.toString()).sessions).toHaveLength(1)
    async function resetAndRestore(mode: 'merge' | 'replace') {
      await page.getByRole('link', { name: /settings/i }).first().click()
      await page.locator('a[href="/settings/reset"]').click()
      await page.getByTestId('reset-local-data').click()
      await page.getByTestId('reset-confirm').click()
      await page.getByRole('link', { name: 'Settings' }).click()
      await page.getByRole('link', { name: /backups/i }).click()
      await uploadBackupFromMemory(page, backup)
      await expect(page.getByTestId('backup-preview')).toBeVisible()
      if (mode === 'merge') await page.getByTestId('backup-merge').click()
      else { await page.getByTestId('backup-replace').click(); await page.getByTestId('replace-confirm').click() }
      await expect(page.getByText(new RegExp(`${mode === 'merge' ? 'Merged' : 'Replaced'} backup`, 'i'))).toBeVisible()
    }
    await resetAndRestore('merge')
    await page.getByRole('link', { name: 'History' }).click()
    await expect(page.getByTestId(/history-session-/)).toHaveCount(1)
    expect((await page.getByTestId('history-list').innerText()).trim()).toBe(historyBefore)
    await resetAndRestore('replace')
    await page.getByRole('link', { name: 'History' }).click()
    await expect(page.getByTestId(/history-session-/)).toHaveCount(1)
    expect((await page.getByTestId('history-list').innerText()).trim()).toBe(historyBefore)
  })

  test('exports, resets, and restores a backup entirely offline @chromium-only', async ({ page, context }) => {
    await page.addInitScript(() => { Object.defineProperty(Navigator.prototype, 'share', { configurable: true, value: undefined }); Object.defineProperty(Navigator.prototype, 'canShare', { configurable: true, value: undefined }) })
    await completeOnboarding(page)
    await finishWorkoutWithOneSet(page)
    const historyBefore = (await page.getByTestId('history-list').innerText()).trim()
    await page.getByRole('link', { name: 'Settings' }).click()
    await page.getByRole('link', { name: /backups/i }).click()
    await context.setOffline(true)
    const downloadPromise = page.waitForEvent('download')
    await page.getByTestId('backup-export').click()
    const download = await downloadPromise
    const backupPath = await download.path()
    expect(backupPath).toBeTruthy()
    const backup = await readFile(backupPath as string)
    await page.getByRole('link', { name: /settings/i }).first().click()
    await page.locator('a[href="/settings/reset"]').click()
    await page.getByTestId('reset-local-data').click()
    await page.getByTestId('reset-confirm').click()
    await page.getByRole('link', { name: 'Settings' }).click()
    await page.getByRole('link', { name: /backups/i }).click()
    await uploadBackupFromMemory(page, backup)
    await expect(page.getByTestId('backup-preview')).toBeVisible()
    await page.getByTestId('backup-merge').click()
    await expect(page.getByText(/merged backup/i)).toBeVisible()
    await page.getByRole('link', { name: 'History' }).click()
    expect((await page.getByTestId('history-list').innerText()).trim()).toBe(historyBefore)
  })

  test('a complete written workout remains usable offline', async ({ page, context }) => {
    await completeOnboarding(page)
    await context.setOffline(true)
    await page.getByTestId('start-workout').click()
    await page.getByRole('button', { name: /start working sets/i }).click()
    await expect(page.getByTestId('offline-status')).toContainText(/offline/i)
    await expect(page.getByTestId('active-exercise')).toBeVisible()
    for (let index = 0; index < 12; index += 1) {
      await saveOneSetAndAdvance(page)
      const next = page.getByRole('button', { name: /next exercise/i })
      if (await next.isVisible()) await next.click()
      else break
    }
    await page.getByTestId('finish-workout').click()
    await expect(page.getByRole('heading', { name: /cool down/i })).toBeVisible()
    await page.getByRole('button', { name: 'Finish workout', exact: true }).click()
    await page.getByTestId('finish-confirm').click()
    await expect(page).toHaveURL(/\/history$/)
  })
})
