import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import type { AppMeta, Band, BackupEnvelope, BackupData, Profile, ScheduleMode, Substitution, Weekday, WorkoutSession } from '../../domain/types'
import { parseBackup, createBackupEnvelope } from '../../domain/backup/backup'
import { validateSubstitution } from '../../domain/substitutions'
import { validateScheduleSettings, resolveSchedule } from '../../domain/schedule'
import { createDefaultBands } from '../../domain/bands'
import { useStorage } from '../../app/providers/AppProvider'
import { browserTimezone, CURRENT_DATABASE_VERSION, getStorageEstimate, isValidIanaTimezone, requestPersistentStorage } from '../../lib/browser'
import { readBackupFile, shareJson } from '../../lib/files'
import { newId, nowIso } from '../../lib/ids'
import { exercises, plan } from '../../lib/content'
import { Button, Card, Dialog, Status } from '../../components/ui/Status'

const weekdays: Array<[Weekday, string]> = [[0, 'Sun'], [1, 'Mon'], [2, 'Tue'], [3, 'Wed'], [4, 'Thu'], [5, 'Fri'], [6, 'Sat']]
const settingLinks = [['/settings/schedule', 'Schedule', 'Choose two or three days and flexible or fixed assignments.'], ['/settings/bands', 'Bands', 'Manage the Serious Steel set and labels.'], ['/settings/substitutions', 'Substitutions', 'Swap within compatible movement categories.'], ['/settings/backups', 'Backups', 'Export, restore, or reset local data.'], ['/settings/storage', 'Storage', 'Review browser persistence and update status.'], ['/settings/reset', 'Reset local data', 'Clear this browser after exporting a backup.']] as const

export function Settings() {
  const storage = useStorage(); const [meta, setMeta] = useState<AppMeta>(); const [sessions, setSessions] = useState<WorkoutSession[]>([])
  useEffect(() => { void Promise.all([Promise.resolve(storage.getAppMeta()), Promise.resolve(storage.listSessions({ status: 'completed' }))]).then(([nextMeta, nextSessions]) => { setMeta(nextMeta); setSessions(nextSessions ?? []) }) }, [storage])
  const completedSinceExport = meta?.lastSuccessfulExportAt ? sessions.filter((session) => (session.completedAt ?? session.updatedAt) > meta.lastSuccessfulExportAt!).length : sessions.length
  const exportDue = sessions.length > 0 && (!meta?.lastSuccessfulExportAt || completedSinceExport >= 5 || (Date.now() - new Date(meta.lastSuccessfulExportAt).getTime()) >= 7 * 24 * 60 * 60 * 1000)
  return <div className="page"><p className="eyebrow">Keep your setup current</p><h2>Settings</h2><Card><h3>Recovery reminder</h3><p>{meta?.lastSuccessfulExportAt ? `Last successful backup: ${new Date(meta.lastSuccessfulExportAt).toLocaleDateString()}. Export again after five workouts or within seven days.` : 'No successful backup is recorded yet. Export after your first completed workout.'}</p>{exportDue && <Status kind="warning" testId="backup-reminder">Your local history is due for a backup. Export it to Files or iCloud Drive.</Status>}<p className="muted">Data stays on this browser. There is no automatic cloud backup.</p></Card><div className="settings-list">{settingLinks.map(([to, title, text]) => <Link className="settings-row" to={to} key={to}><strong>{title}</strong><span>{text}</span><span aria-hidden="true">→</span></Link>)}</div></div>
}

function useProfile() { const storage = useStorage(); const [profile, setProfile] = useState<Profile>(); useEffect(() => { void Promise.resolve(storage.getProfile()).then(setProfile) }, [storage]); return { storage, profile, setProfile } }

function targetKind(exercise: (typeof exercises)[number]): 'reps' | 'duration' { return exercise.defaultTarget.repRange ? 'reps' : 'duration' }

export function ScheduleSettings() {
  const { storage, profile, setProfile } = useProfile(); const [sessions, setSessions] = useState<WorkoutSession[]>([]); const [days, setDays] = useState<2 | 3>(3); const [mode, setMode] = useState<ScheduleMode>('flexible'); const [fixed, setFixed] = useState<Weekday[]>([1, 3, 5]); const [timezone, setTimezone] = useState(browserTimezone()); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { if (!profile) return; setDays(profile.daysPerWeek); setMode(profile.mode); setFixed([...new Set(profile.fixedWeekdays)]); setTimezone(profile.timezone) }, [profile])
  useEffect(() => { void Promise.resolve(storage.listSessions()).then((items) => setSessions(items ?? [])) }, [storage])
  const schedule = useMemo(() => ({ timezone, daysPerWeek: days, mode, fixedWeekdays: mode === 'fixed' ? fixed : [] as Weekday[] }), [days, fixed, mode, timezone])
  const validation = useMemo(() => validateScheduleSettings(schedule), [schedule])
  const preview = useMemo(() => { if (!validation.valid) return undefined; try { return resolveSchedule({ settings: schedule, now: new Date(), sessions }) } catch { return undefined } }, [schedule, sessions, validation.valid])
  function toggleDay(day: Weekday) { setFixed((current) => current.includes(day) ? current.filter((item) => item !== day) : [...new Set([...current, day])].sort() as Weekday[]) }
  async function save() {
    setMessage(''); setError('')
    if (!profile) { setError('Complete onboarding before changing the schedule.'); return }
    if (!isValidIanaTimezone(timezone) || !validation.valid) { setError(validation.errors.join(' ') || 'Choose a valid IANA timezone.'); return }
    const next = { ...profile, daysPerWeek: days, mode, fixedWeekdays: mode === 'fixed' ? [...new Set(fixed)].sort() as Weekday[] : [], timezone, updatedAt: nowIso() }
    try { await storage.saveProfile(next); setProfile(next); setMessage('Schedule saved. Completed history was not changed.') } catch { setError('Schedule could not be saved. Your previous settings remain active.') }
  }
  return <div className="page"><Link to="/settings" className="text-button">← Settings</Link><h2>Schedule</h2><Card><h3>Training days</h3><div className="choice-grid"><button type="button" className={days === 2 ? 'choice selected' : 'choice'} onClick={() => setDays(2)} aria-pressed={days === 2}>2 days<span>A → B</span></button><button type="button" className={days === 3 ? 'choice selected' : 'choice'} onClick={() => setDays(3)} aria-pressed={days === 3}>3 days<span>A → B → C</span></button></div><h3>Assignment</h3><div className="choice-grid"><button type="button" className={mode === 'flexible' ? 'choice selected' : 'choice'} onClick={() => setMode('flexible')} aria-pressed={mode === 'flexible'}>Flexible<span>When ready; missed days do not become overdue.</span></button><button type="button" className={mode === 'fixed' ? 'choice selected' : 'choice'} onClick={() => setMode('fixed')} aria-pressed={mode === 'fixed'}>Fixed<span>Selected weekdays stay assigned.</span></button></div>{mode === 'fixed' && <fieldset><legend>Choose exactly {days} unique weekdays</legend><div className="weekday-grid">{weekdays.map(([day, label]) => <label className="check" key={day}><input type="checkbox" checked={fixed.includes(day)} onChange={() => toggleDay(day)} />{label}</label>)}</div></fieldset>}<label htmlFor="schedule-timezone">Saved timezone<input id="schedule-timezone" value={timezone} onChange={(event) => setTimezone(event.target.value)} aria-describedby="schedule-timezone-help" /></label><p id="schedule-timezone-help" className="help">Use an IANA timezone such as America/Toronto.</p>{!validation.valid && <Status kind="error">{validation.errors.join(' ')}</Status>}<Button onClick={() => void save()}>Save schedule</Button>{message && <Status kind="success">{message}</Status>}{error && <Status kind="error">{error}</Status>}</Card><Card><h3>Next assignment preview</h3>{preview?.resume ? <p>Resume Workout {preview.resume.workoutKey} from {preview.resume.scheduledDate}.</p> : preview?.next ? <p>Next: Workout {preview.next.workoutKey} on {preview.next.scheduledDate} ({weekdays[preview.next.weekday][1]}). {preview.missed.length ? `${preview.missed.length} earlier fixed-day session${preview.missed.length === 1 ? '' : 's'} can be completed late or skipped.` : 'No missed assignment.'}</p> : <p className="muted">Complete the schedule fields to preview the next assignment.</p>}</Card></div>
}

export function BandsSettings() {
  const storage = useStorage(); const [bands, setBands] = useState<Band[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState(''); useEffect(() => { void Promise.resolve(storage.getBands()).then((items) => setBands(items.length ? items : createDefaultBands())) }, [storage])
  async function save() { try { const next = bands.map((band) => ({ ...band, updatedAt: nowIso() })); await storage.replaceBands(next); setBands(next); setMessage('Band inventory saved.'); setError('') } catch { setError('Band inventory could not be saved.') } }
  return <div className="page"><Link to="/settings" className="text-button">← Settings</Link><h2>Bands</h2><Card><p>Band color is paired with number and nominal range. Ranges vary with stretch and setup; they are not fixed weights.</p>{bands.map((band) => <div className="band-row editable" key={band.key}><span className={`band-dot band-${band.displayColor}`} aria-hidden="true" /><strong>{band.displayColor} #{band.number}</strong><span>{band.nominalMinLb}–{band.nominalMaxLb} lb nominal</span><label className="inline-check"><input type="checkbox" checked={band.enabled} onChange={() => setBands((current) => current.map((item) => item.key === band.key ? { ...item, enabled: !item.enabled } : item))} />Available</label><input aria-label={`Nickname for ${band.displayColor} band`} value={band.nickname ?? ''} placeholder="Nickname" onChange={(event) => setBands((current) => current.map((item) => item.key === band.key ? { ...item, nickname: event.target.value } : item))} /></div>)}<Button onClick={() => void save()}>Save bands</Button>{message && <Status kind="success">{message}</Status>}{error && <Status kind="error">{error}</Status>}</Card></div>
}

export function SubstitutionSettings() {
  const storage = useStorage(); const [saved, setSaved] = useState<Substitution[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState(''); useEffect(() => { void Promise.resolve(storage.listSubstitutions()).then(setSaved) }, [storage]); const bySlot = useMemo(() => new Map(saved.map((item) => [item.planSlotId, item])), [saved])
  async function choose(slotId: string, originalId: string, selectedId: string) { const source = exercises.find((exercise) => exercise.id === originalId); const candidate = exercises.find((exercise) => exercise.id === selectedId); if (!source || !candidate) return; const result = validateSubstitution(source, candidate); if (!result.valid || targetKind(source) !== targetKind(candidate)) { setError(result.errors.join(' ') || 'Choose a compatible exercise with the same rep or duration target.'); return } const stamp = nowIso(); const existing = bySlot.get(slotId); const sub: Substitution = { id: existing?.id ?? newId(), planSlotId: slotId, originalExerciseId: originalId, selectedExerciseId: selectedId, createdAt: existing?.createdAt ?? stamp, updatedAt: stamp }; try { await storage.saveSubstitution(sub); setSaved((current) => [...current.filter((item) => item.planSlotId !== slotId), sub]); setError(''); setMessage('Substitution saved; completed history remains under its original exercise.') } catch { setError('Substitution could not be saved.') } }
  async function restore(slotId: string) { try { await storage.removeSubstitution(slotId); setSaved((current) => current.filter((item) => item.planSlotId !== slotId)); setMessage('Default exercise restored.'); setError('') } catch { setError('Default exercise could not be restored.') } }
  return <div className="page"><Link to="/settings" className="text-button">← Settings</Link><h2>Substitutions</h2><Card><p>Choose only movements in the compatible category and with the same rep or duration target. A current swap never rewrites completed history.</p>{Object.values(plan.workouts).flat().filter((slot) => /^[ABC]-[1-6]$/.test(slot.id)).map((slot) => { const source = exercises.find((exercise) => exercise.id === slot.exerciseId); const alternatives = exercises.filter((exercise) => source && validateSubstitution(source, exercise).valid && targetKind(source) === targetKind(exercise) && exercise.id !== source.id); const selected = bySlot.get(slot.id)?.selectedExerciseId ?? slot.exerciseId; return <div className="substitution-row" data-testid={`substitution-row-${slot.id}`} key={slot.id}><label htmlFor={`substitution-${slot.id}`}>{source?.name ?? slot.exerciseId}<select id={`substitution-${slot.id}`} value={selected} onChange={(event) => void choose(slot.id, slot.exerciseId, event.target.value)} data-testid="substitution-select"><option value={slot.exerciseId}>{source?.name ?? slot.exerciseId} (default)</option>{alternatives.map((candidate) => <option value={candidate.id} key={candidate.id}>{candidate.name}</option>)}</select></label>{bySlot.has(slot.id) && <button type="button" className="text-button" onClick={() => void restore(slot.id)} data-testid="restore-substitution">Restore default</button>}</div> })}{message && <Status kind="success">{message}</Status>}{error && <Status kind="error">{error}</Status>}</Card></div>
}

function dateRange(sessions: BackupEnvelope['sessions']): string { const dates = sessions.map((session) => session.scheduledDate).sort(); return dates.length ? `${dates[0]} to ${dates[dates.length - 1]}` : 'no workout dates' }

export function BackupSettings() {
  const storage = useStorage(); const fileRef = useRef<HTMLInputElement>(null); const replaceTriggerRef = useRef<HTMLButtonElement>(null); const [preview, setPreview] = useState<BackupEnvelope>(); const [raw, setRaw] = useState<BackupData>(); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [replaceConfirm, setReplaceConfirm] = useState(false); const [busy, setBusy] = useState(false)
  async function exportBackup() { setBusy(true); setError(''); setMessage(''); try { const data = await storage.exportData(); const envelope = await createBackupEnvelope(data, { appVersion: '0.1.0', exportedAt: nowIso() }); await shareJson(`training-tracker-backup-${new Date().toISOString().slice(0, 10)}.json`, envelope); const meta = await Promise.resolve(storage.getAppMeta()); const stamp = nowIso(); await storage.saveAppMeta(meta ? { ...meta, lastSuccessfulExportAt: envelope.exportedAt, updatedAt: stamp } : { id: 'app', databaseVersion: CURRENT_DATABASE_VERSION, dismissedNotices: [], lastSuccessfulExportAt: envelope.exportedAt, createdAt: stamp, updatedAt: stamp }); setMessage('Backup exported. Save it to Files or iCloud Drive.') } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : 'Backup export failed. Your local data was not changed.') } finally { setBusy(false) } }
  async function readFile(file?: File) { if (!file) return; setError(''); setMessage(''); try { const envelope = await parseBackup(await readBackupFile(file).then((value) => JSON.stringify(value)), { knownExerciseIds: new Set(exercises.map((exercise) => exercise.id)), knownPlanSlotIds: new Set(Object.values(plan.workouts).flat().map((slot) => slot.id)) }); setPreview(envelope); setRaw({ profile: envelope.profile, bands: envelope.bands, substitutions: envelope.substitutions, sessions: envelope.sessions, exerciseLogs: envelope.exerciseLogs, setLogs: envelope.setLogs, appMeta: envelope.appMeta }) } catch (cause: unknown) { setPreview(undefined); setRaw(undefined); setError(cause instanceof Error ? cause.message : 'This backup is malformed or from an unsupported version.') } finally { if (fileRef.current) fileRef.current.value = '' } }
  async function importBackup(mode: 'merge' | 'replace') { if (!raw) return; setBusy(true); setError(''); try { const report = await storage.importData(mode, raw); setMessage(`${mode === 'merge' ? 'Merged' : 'Replaced'} backup: ${report.sessions} workouts, ${report.inserted} records added.`); setPreview(undefined); setRaw(undefined) } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : 'Import failed. Your local data was restored and no partial changes were kept.') } finally { setBusy(false) } }
  return <div className="page"><Link to="/settings" className="text-button">← Settings</Link><h2>Backups</h2><Card><p>Manual JSON backups protect local history if Safari website data is deleted or you change phones. There is no automatic cloud backup.</p><p className="muted">Reminder: export after five additional workouts or seven days without a successful export.</p><div className="form-actions"><Button onClick={() => void exportBackup()} disabled={busy} data-testid="backup-export">{busy ? 'Working…' : 'Export backup'}</Button><Button variant="secondary" onClick={() => fileRef.current?.click()} disabled={busy}>Choose backup file</Button><input className="sr-only" ref={fileRef} type="file" accept="application/json,.json" onChange={(event) => void readFile(event.target.files?.[0])} data-testid="backup-file-input" /></div>{preview && <div className="backup-preview" data-testid="backup-preview"><h3>Restore preview</h3><p>{preview.sessions.length} workouts · {dateRange(preview.sessions)} · {preview.bands.length} bands · exported {preview.exportedAt}</p><p>Default action is <strong>Merge</strong>: UUID records are deduplicated and the latest updated record is kept.</p><div className="form-actions"><Button onClick={() => void importBackup('merge')} disabled={busy} data-testid="backup-merge">Merge (recommended)</Button><Button ref={replaceTriggerRef} variant="danger" onClick={() => setReplaceConfirm(true)} disabled={busy} data-testid="backup-replace">Replace all local data</Button><Button variant="ghost" onClick={() => { setPreview(undefined); setRaw(undefined) }} data-testid="backup-cancel">Cancel</Button></div></div>}{error && <Status kind="error" testId="backup-error">{error}</Status>}{message && <Status kind="success">{message}</Status>}</Card>{replaceConfirm && <Dialog title="Replace all local data?" returnFocusRef={replaceTriggerRef} onClose={() => setReplaceConfirm(false)} actions={<><Button variant="secondary" onClick={() => setReplaceConfirm(false)}>Cancel</Button><Button variant="danger" onClick={() => { setReplaceConfirm(false); void importBackup('replace') }} data-testid="replace-confirm">Replace all</Button></>}><p>This is the second confirmation. It replaces the current profile, bands, substitutions, sessions, logs, and metadata with the validated backup. A safety snapshot is taken by the adapter first.</p></Dialog>}</div>
}

export function StorageSettings() {
  const storage = useStorage(); const [persistent, setPersistent] = useState<boolean | undefined>(); const [requested, setRequested] = useState(false); const [estimate, setEstimate] = useState<{ usageBytes?: number; quotaBytes?: number }>({}); const [message, setMessage] = useState(''); const [error, setError] = useState(''); useEffect(() => { void Promise.all([storage.getStorageStatus ? storage.getStorageStatus() : Promise.resolve(undefined), getStorageEstimate()]).then(([status, browserEstimate]) => { setPersistent(status?.persistentGranted); setRequested(status?.persistentRequested ?? false); setEstimate({ usageBytes: status?.usageBytes ?? browserEstimate.usageBytes, quotaBytes: status?.quotaBytes ?? browserEstimate.quotaBytes }) }).catch(() => setError('Storage status is unavailable.')) }, [storage])
  async function persist() { try { const result = await requestPersistentStorage(); setPersistent(result); setMessage(result === true ? 'Persistent storage granted by the browser.' : 'The browser did not grant persistent storage; keep a manual backup.') } catch { setError('The browser could not evaluate persistent storage.') } }
  return <div className="page"><Link to="/settings" className="text-button">← Settings</Link><h2>Storage</h2><Card><h3>Local storage status</h3><p data-testid="storage-status">Persistent storage: {persistent === undefined ? 'unknown' : persistent ? 'granted' : 'not granted'}{requested ? '' : ' (request unavailable)'}</p><p className="muted">{estimate.usageBytes !== undefined ? `${Math.round(estimate.usageBytes / 1024)} KB used` : 'Usage estimate unavailable.'}{estimate.quotaBytes ? ` of ${Math.round(estimate.quotaBytes / 1024 / 1024)} MB quota` : ''}</p><Button variant="secondary" onClick={() => void persist()} disabled={!requested}>Request persistent storage</Button>{message && <Status kind="info">{message}</Status>}{error && <Status kind="error">{error}</Status>}</Card><Card><h3>Important recovery note</h3><p>Deleting Safari website data, uninstalling this PWA, or changing its production domain can remove access to unexported history. Export to Files or iCloud Drive regularly.</p></Card></div>
}

export function ResetSettings() {
  const storage = useStorage(); const navigate = useNavigate(); const resetTriggerRef = useRef<HTMLButtonElement>(null); const [confirm, setConfirm] = useState(false); const [error, setError] = useState(''); async function reset() { try { await storage.resetAllData(); navigate('/onboarding', { replace: true }) } catch { setError('Reset failed. Your local data was not changed.') } }
  return <div className="page"><h2>Reset local data</h2><Card><p>This permanently clears this browser’s profile, workouts, bands, substitutions, and backup metadata. Export first if you may need the history.</p><Button ref={resetTriggerRef} variant="danger" onClick={() => setConfirm(true)} data-testid="reset-local-data">Reset local data</Button>{error && <Status kind="error">{error}</Status>}</Card>{confirm && <Dialog title="Reset all local data?" returnFocusRef={resetTriggerRef} onClose={() => setConfirm(false)} actions={<><Button variant="secondary" onClick={() => setConfirm(false)} data-testid="reset-cancel">Cancel</Button><Button variant="danger" onClick={() => void reset()} data-testid="reset-confirm">Reset everything</Button></>}><p>This action cannot be undone from this browser. This is the final confirmation.</p></Dialog>}</div>
}
