import type { Exercise, ExerciseMedia, MovementPattern, Target } from './types'
import { CONTENT_VERSION, MEDIA_VERIFIED_ON } from './types'

const video = (
  videoId: string,
  title: string,
  source: string,
  equipmentFit: ExerciseMedia['equipmentFit'],
  fitNote: string,
  url = `https://www.youtube.com/watch?v=${videoId}`,
): ExerciseMedia => ({
  provider: 'youtube',
  videoId,
  url,
  title,
  source,
  verifiedOn: MEDIA_VERIFIED_ON,
  equipmentFit,
  lazy: true,
  attribution: `${source} — YouTube`,
  fitNote,
})

type ExerciseInput = Omit<Exercise, 'contentVersion'>

const make = (input: ExerciseInput): Exercise => ({ ...input, contentVersion: CONTENT_VERSION })

const bandSetup = (placement: string): string[] => [
  `Use one intact 41-inch continuous loop; ${placement}.`,
  'No door anchor, furniture anchor, handles, or improvised attachment is used.',
]

const bodySetup = (setup: string): string[] => [setup, 'Clear the floor and keep a stable support nearby when balance is uncertain.']

const bandWarnings = ['Inspect the loop for tears before each set.', 'Stop if the band slips toward the neck, face, or a painful joint.', 'Use a light enough band to release without a snap.']

const mediaFit = 'Visual recheck on 2026-08-16 matched the stated movement and no-anchor intent.'
const seatedRowMediaFit = 'Visual recheck on 2026-08-16: the YouTube thumbnail clearly shows one continuous loop around both feet with no door/furniture anchor or handles; the video description identifies the feet-wrapped no-anchor alternative, matching the 41-inch-style loop setup.'

export const exercises: Exercise[] = [
  make({ id: 'lower-front-squat-band', name: 'Band front squat', category: 'squat', movementPattern: 'squat', setup: bandSetup('stand on its midpoint and rest the other half across the upper shoulders/traps, never the throat'), steps: ['Brace and sit down and slightly back while knees track over the middle toes.', 'Descend only while feet stay flat and spine stays neutral.', 'Drive through the whole foot to stand tall.'], breathingTempo: 'Inhale on a 2–3-second descent; exhale on a controlled ascent.', primaryMuscles: ['quadriceps', 'gluteus maximus'], secondaryMuscles: ['adductors', 'hamstrings', 'trunk'], formCues: ['Tripod foot', 'knees follow toes', 'ribs stack over pelvis', 'band stays on shoulders', 'push the floor away'], commonMistakes: ['Band on neck', 'heels lifting', 'knees collapsing inward', 'dropping quickly'], easierVariations: ['Chair squat', 'bodyweight squat', 'lighter loop'], harderVariations: ['Shorten the grip', '3-second eccentric', 'second loop only after safe release is mastered'], bandWarnings, compatibleSubstitutionCategories: ['squat', 'lunge'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('5K-KlUlPo40', 'How to | Resistance Band Front Squat', 'OMNI Strength and Performance', '41-inch-loop-no-anchor', mediaFit) }),
  make({ id: 'upper-row-seated-feet', name: 'Seated band row around feet', category: 'pull-horizontal', movementPattern: 'pull-horizontal', setup: bandSetup('sit tall with the loop around the balls of both feet and hold both sides'), steps: ['Brace tall and pull elbows toward the ribs.', 'Pause with shoulder blades gently back and down.', 'Return hands slowly without rounding or letting the feet slide.'], breathingTempo: 'Exhale on the 1–2-second pull; inhale on a 2–3-second return.', primaryMuscles: ['lats', 'rhomboids', 'middle trapezius'], secondaryMuscles: ['biceps', 'rear deltoids'], formCues: ['Chest tall', 'elbows to ribs', 'shoulders away from ears', 'feet stay planted', 'quiet return'], commonMistakes: ['Shrugging', 'leaning backward', 'rounding the spine', 'yanking the band'], easierVariations: ['Shorter range', 'lighter loop', 'seated bodyweight scapular row'], harderVariations: ['Shorten grip', '2-second squeeze', 'staggered-leg seated row'], bandWarnings, compatibleSubstitutionCategories: ['pull-horizontal', 'pull-apart'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('PKZW3s3G_Y0', 'How to Do Seated Rows with Resistance Bands! (With and without an Anchor)', 'Scott Abel Coaching', '41-inch-loop-no-anchor', seatedRowMediaFit) }),
  make({ id: 'lower-rdl-band', name: 'Band Romanian deadlift', category: 'hinge', movementPattern: 'hinge', setup: bandSetup('stand on the midpoint with feet hip-width and hold the opposite half in both hands'), steps: ['Soften the knees and push hips back with a long spine.', 'Lower only to the point of hamstring tension without losing foot pressure.', 'Drive hips forward to stand without leaning back.'], breathingTempo: 'Inhale and brace before a 2–3-second hinge; exhale on the rise.', primaryMuscles: ['hamstrings', 'gluteus maximus'], secondaryMuscles: ['erectors', 'adductors', 'upper back'], formCues: ['Hips travel back', 'band close to legs', 'soft knees', 'sternum and pelvis move together', 'finish tall'], commonMistakes: ['Squatting instead of hinging', 'rounding', 'locking knees', 'bouncing'], easierVariations: ['Wall hip-hinge drill', 'lighter band'], harderVariations: ['Shorter grip', 'bottom pause', 'staggered stance'], bandWarnings, compatibleSubstitutionCategories: ['hinge', 'squat'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('SPXnuQjOz0E', 'Resistance Band RDL Tutorial', 'Band Bar Studios', '41-inch-loop-no-anchor', mediaFit) }),
  make({ id: 'upper-pushup-band', name: 'Band-resisted push-up', category: 'push-horizontal', movementPattern: 'push-horizontal', setup: bandSetup('place the loop across the upper back and pass each side under the palms; use an incline or knees to regress'), steps: ['Set hands just outside the shoulders and brace glutes and ribs.', 'Lower chest between hands with elbows about 30–45 degrees from the body.', 'Press the floor away as the torso moves as one unit.'], breathingTempo: 'Inhale on a 2–3-second lower; exhale on the press.', primaryMuscles: ['chest', 'triceps', 'anterior deltoid'], secondaryMuscles: ['serratus anterior', 'trunk'], formCues: ['Band across shoulder blades', 'hands under shoulders', 'ribs and hips rise together', 'elbows track', 'push the floor away'], commonMistakes: ['Band around neck', 'hips sagging', 'hands too wide', 'elbows flaring'], easierVariations: ['Wall or counter incline', 'knees', 'bodyweight push-up'], harderVariations: ['Lower the incline', 'shorten the loop', 'controlled bottom pause'], bandWarnings, compatibleSubstitutionCategories: ['push-horizontal', 'push-vertical'], defaultTarget: { kind: 'reps', min: 6, max: 10 }, media: video('vFTIpxW_SMY', 'Chest & Triceps with Dumbbells and Bands', 'James Grage', '41-inch-loop-no-anchor', 'Time-stamped segment visually shows loop across back and under hands; YouTube channel metadata identifies James Grage.', 'https://www.youtube.com/watch?v=vFTIpxW_SMY&t=29s') }),
  make({ id: 'upper-press-overhead-band', name: 'Standing band overhead press', category: 'push-vertical', movementPattern: 'push-vertical', setup: bandSetup('stand on the middle with one or both feet and hold the opposite half at shoulder height'), steps: ['Stack ribs over pelvis and keep wrists over elbows.', 'Press vertically without shrugging or arching.', 'Lower slowly to shoulder height while retaining tension.'], breathingTempo: 'Inhale at the start; exhale through a 1–2-second press and inhale on the 2–3-second lower.', primaryMuscles: ['deltoids', 'triceps'], secondaryMuscles: ['upper chest', 'serratus', 'trunk'], formCues: ['Feet own the band', 'elbows slightly forward', 'ribs down', 'straight press path', 'neck long'], commonMistakes: ['Band behind neck', 'backbend', 'elbows flaring', 'starting with slack'], easierVariations: ['One-arm press', 'seated press', 'bodyweight reach'], harderVariations: ['Shorten grip', 'staggered stance', 'overhead pause'], bandWarnings, compatibleSubstitutionCategories: ['push-vertical', 'push-horizontal'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('_nT3G-5f74k', 'Full Body Resistance Band Training — Shoulder Press', 'Undersun Fitness', '41-inch-loop-no-anchor', 'Visual frame at 6:37 shows a continuous loop under the feet and pressing overhead.', 'https://www.youtube.com/watch?v=_nT3G-5f74k&t=397s') }),
  make({ id: 'core-dead-bug', name: 'Dead bug', category: 'core', movementPattern: 'core', setup: bodySetup('Lie on your back with hips and knees at 90 degrees, arms toward the ceiling, and pelvis quiet.'), steps: ['Brace gently and lower the opposite arm and leg.', 'Keep the back heavy and return before the pelvis moves.', 'Alternate sides; use heel taps for a regression.'], breathingTempo: 'Exhale during each reach; inhale on return with a 3-second reach.', primaryMuscles: ['deep abdominals', 'rectus abdominis'], secondaryMuscles: ['hip flexors', 'shoulder stabilizers'], formCues: ['Back stays heavy', 'ribs down', 'move opposite limbs', 'small range is valid', 'quiet pelvis'], commonMistakes: ['Lumbar arch', 'moving too quickly', 'shrugging', 'forcing range'], easierVariations: ['Heel taps', 'one limb at a time'], harderVariations: ['Longer lever', 'slower eccentric', 'light loop at feet'], bandWarnings: ['Optional band is not a V1 requirement.', 'Stop for back pain or abdominal doming.', 'Do not sacrifice pelvic control for range.'], compatibleSubstitutionCategories: ['core'], defaultTarget: { kind: 'reps', min: 6, max: 10, perSide: true }, media: video('GbSC02oU3To', 'Dead Bug', 'Hinge Health', 'bodyweight-no-anchor', 'Clinical bodyweight demonstration exactly matches the default setup.') }),
  make({ id: 'lower-reverse-lunge', name: 'Reverse lunge', category: 'lunge', movementPattern: 'lunge', setup: bodySetup('Stand hip-width with a wall or chair within reach; bodyweight is the V1 load.'), steps: ['Step one foot straight back and land softly.', 'Bend both knees under control to a comfortable depth.', 'Drive through the front whole foot to return.'], breathingTempo: 'Inhale stepping and lowering for 2–3 seconds; exhale to rise.', primaryMuscles: ['quadriceps', 'gluteus maximus'], secondaryMuscles: ['adductors', 'hamstrings', 'calves', 'trunk'], formCues: ['Train-track stance', 'front foot flat', 'knee follows toes', 'torso tall', 'quiet return'], commonMistakes: ['Tightrope stance', 'heel lifting', 'knee cave', 'dropping onto the rear knee'], easierVariations: ['Supported toe tap', 'reduced depth'], harderVariations: ['Full depth', 'slower eccentric', 'light band only after control'], bandWarnings: ['Start bodyweight as prescribed.', 'Do not add a loop while balance is unreliable.', 'Use stable support.'], compatibleSubstitutionCategories: ['lunge', 'squat'], defaultTarget: { kind: 'reps', min: 6, max: 10, perSide: true }, media: video('6rKA_et3dGk', 'Reverse Lunge', 'Hinge Health', 'bodyweight-no-anchor', 'Clinical bodyweight step-back lunge exactly matches V1.') }),
  make({ id: 'upper-floor-press-band', name: 'Band floor press', category: 'push-horizontal', movementPattern: 'push-horizontal', setup: bandSetup('lie with knees bent and pass the loop under the shoulder blades/upper back; hold both sides in the hands'), steps: ['Set shoulder blades gently down and wrists over elbows.', 'Press toward the ceiling until arms are nearly straight.', 'Lower until upper arms lightly touch the floor without losing symmetry.'], breathingTempo: 'Inhale on a 2–3-second lower; exhale through the press.', primaryMuscles: ['chest', 'triceps'], secondaryMuscles: ['anterior deltoid', 'trunk'], formCues: ['Band under shoulder blades', 'wrists over elbows', 'feet planted', 'elbows 30–45 degrees', 'press up'], commonMistakes: ['Band at neck', 'elbows flaring', 'bent wrists', 'feet sliding'], easierVariations: ['Lighter loop', 'incline push-up'], harderVariations: ['Shorten grip', 'pause at the floor', 'alternating press only when stable'], bandWarnings, compatibleSubstitutionCategories: ['push-horizontal', 'push-vertical'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('L08vWPkMftQ', 'Resistance Band Lying Chest Press', 'Fit Gent', '41-inch-loop-no-anchor', 'Visual frame at 0:52 shows a continuous loop under the upper back and no door anchor.', 'https://www.youtube.com/watch?v=L08vWPkMftQ&t=50s') }),
  make({ id: 'lower-good-morning-band', name: 'Band good morning', category: 'hinge', movementPattern: 'hinge', setup: bandSetup('stand on the loop and bring the other half behind the upper shoulders/traps, away from the neck'), steps: ['Unlock knees and push hips back with a braced trunk.', 'Hinge only while the spine stays neutral.', 'Drive hips forward to stand tall.'], breathingTempo: 'Inhale and brace before a 2–3-second hinge; exhale as hips extend.', primaryMuscles: ['hamstrings', 'gluteus maximus', 'erectors'], secondaryMuscles: ['adductors', 'upper back'], formCues: ['Hips back', 'band on traps', 'knees soft', 'spine long', 'squeeze glutes'], commonMistakes: ['Squatting down', 'rounding', 'band on cervical spine', 'arching to finish'], easierVariations: ['Bodyweight hinge', 'band RDL'], harderVariations: ['Shorten grip', 'pause', 'slightly wider stance'], bandWarnings, compatibleSubstitutionCategories: ['hinge'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('7PKCrUmE0NE', 'Banded Good Mornings | Exercise Demo', 'SET FOR SET', '41-inch-loop-no-anchor', 'Visual recheck on 2026-08-16 shows a continuous loop under both feet and across the upper traps, with no anchor; YouTube metadata identifies SET FOR SET as the channel.') }),
  make({ id: 'upper-row-bentover-band', name: 'Bent-over band row', category: 'pull-horizontal', movementPattern: 'pull-horizontal', setup: bandSetup('stand on the middle with feet hip-width, hold the other half, and hinge 30–45 degrees'), steps: ['Brace and pull elbows toward hips while the torso angle stays fixed.', 'Pause without shrugging.', 'Lower hands until arms are long without losing tension.'], breathingTempo: 'Exhale on the 1–2-second row; inhale on a 2–3-second return.', primaryMuscles: ['lats', 'rhomboids', 'middle trapezius'], secondaryMuscles: ['biceps', 'rear deltoids', 'erectors'], formCues: ['Chest long', 'hips back', 'elbows to pockets', 'neck follows spine', 'no swing'], commonMistakes: ['Standing upright', 'rounding', 'shrugging', 'yanking'], easierVariations: ['Higher torso angle', 'seated row'], harderVariations: ['Shorter grip', 'top pause', 'staggered stance'], bandWarnings, compatibleSubstitutionCategories: ['pull-horizontal', 'pull-apart'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('Qid9sie2XLs', 'Resistance Band Bent-Over Row', 'FITINSANE', '41-inch-loop-no-anchor', 'Thumbnail and video title match a hinged, feet-under-loop row; YouTube channel metadata identifies FITINSANE.') }),
  make({ id: 'upper-pull-apart-band', name: 'Band pull-apart', category: 'pull-apart', movementPattern: 'pull-apart', setup: bandSetup('hold it in both hands at shoulder height with arms straight or softly bent and light starting tension'), steps: ['Keep ribs stacked and pull hands laterally until the loop approaches the chest.', 'Pause while shoulder blades move without shrugging.', 'Return slowly without a snap.'], breathingTempo: 'Exhale while opening; inhale through a 2–3-second return.', primaryMuscles: ['rear deltoids', 'rhomboids', 'middle trapezius'], secondaryMuscles: ['rotator cuff', 'trunk'], formCues: ['Shoulders away from ears', 'ribs down', 'hands move sideways', 'squeeze between blades', 'quiet return'], commonMistakes: ['Shrugging', 'arching', 'bending elbows into a row', 'using too-heavy a band'], easierVariations: ['Wider grip', 'lighter band'], harderVariations: ['Narrower grip', '2-second hold'], bandWarnings, compatibleSubstitutionCategories: ['pull-apart', 'pull-horizontal'], defaultTarget: { kind: 'reps', min: 8, max: 15 }, media: video('WqdNDTTe-9g', 'Resistance Band Pull Apart', 'FIT.nl', '41-inch-loop-no-anchor', mediaFit) }),
  make({ id: 'core-side-plank', name: 'Side plank', category: 'core', movementPattern: 'core', setup: bodySetup('Lie on one side with elbow under shoulder, knees bent for regression or legs long for the standard version.'), steps: ['Brace and lift hips until head, shoulders, hips, and knees/feet align.', 'Hold without rotating or shrugging.', 'Lower quietly and switch sides.'], breathingTempo: 'Breathe continuously; use a 15–30-second controlled hold.', primaryMuscles: ['obliques', 'quadratus lumborum'], secondaryMuscles: ['gluteus medius', 'shoulder stabilizers'], formCues: ['Elbow under shoulder', 'hips forward', 'ribs stacked', 'neck long', 'quiet breathing'], commonMistakes: ['Hips sagging', 'shoulder collapsing', 'rotating chest', 'holding breath'], easierVariations: ['Bent-knee side plank', 'side-lying brace'], harderVariations: ['Long-lever plank', 'top-leg lift', 'longer hold'], bandWarnings: ['No band is required.', 'Stop for shoulder pain.', 'Use a padded surface for the elbow.'], compatibleSubstitutionCategories: ['core'], defaultTarget: { kind: 'seconds', min: 15, max: 30, perSide: true }, media: video('qbuqsJ9CuQA', 'Side Plank', 'Hinge Health', 'bodyweight-no-anchor', 'Clinical demonstration matches the bodyweight side-plank default.') }),
  make({ id: 'lower-split-squat', name: 'Split squat', category: 'lunge', movementPattern: 'lunge', setup: bodySetup('Stagger feet on train tracks, keep most weight through the front foot, and use a support if needed.'), steps: ['Lower straight down with both knees bending.', 'Keep the front heel heavy and pelvis square.', 'Press through the front foot to rise.'], breathingTempo: 'Inhale on a 2–3-second lower; exhale to stand.', primaryMuscles: ['quadriceps', 'gluteus maximus'], secondaryMuscles: ['adductors', 'hamstrings', 'trunk'], formCues: ['Wide enough stance', 'front heel heavy', 'knee follows toes', 'torso tall', 'controlled depth'], commonMistakes: ['Narrow stance', 'heel lifting', 'knee caving', 'bouncing'], easierVariations: ['Supported split squat', 'reduced depth'], harderVariations: ['Slower eccentric', 'pause', 'light loop after bodyweight control'], bandWarnings, compatibleSubstitutionCategories: ['lunge', 'squat'], defaultTarget: { kind: 'reps', min: 6, max: 10, perSide: true }, media: video('YxyVk-vRtX8', 'Resistance Band Split Squats', 'TB12 Sports', '41-inch-loop-no-anchor', 'Long-loop-under-foot demonstration; use the bodyweight/support regression first.') }),
  make({ id: 'lower-single-leg-rdl-supported', name: 'Supported single-leg Romanian deadlift', category: 'hinge', movementPattern: 'hinge', setup: bodySetup('Stand beside a wall and use one hand lightly; start bodyweight with the free foot hovering or toe-tapping.'), steps: ['Soften the stance knee and hinge at the stance hip while the free leg reaches back.', 'Keep pelvis square and support hand light.', 'Drive through the stance foot to return.'], breathingTempo: 'Inhale into a 3-second hinge; exhale through the 1–2-second return.', primaryMuscles: ['stance hamstring', 'stance glute'], secondaryMuscles: ['hip stabilizers', 'foot/ankle', 'erectors'], formCues: ['Soft stance knee', 'hips square', 'whole foot grounded', 'support hand light', 'reach long'], commonMistakes: ['Locking knee', 'rotating open', 'free leg too high', 'hauling up with arm'], easierVariations: ['Two-hand wall support', 'kickstand RDL'], harderVariations: ['Less support', 'pause', 'light loop in opposite hand'], bandWarnings: ['Balance, not band strength, is the limiter.', 'Do not add a loop until bodyweight is controlled on both sides.', 'Keep the wall within reach.'], compatibleSubstitutionCategories: ['hinge'], defaultTarget: { kind: 'reps', min: 6, max: 10, perSide: true }, media: video('GZade8_TsSM', 'Single Leg RDL on Wall', 'Movement Library-StrengthHouse', 'bodyweight-no-anchor', 'Visual recheck shows a wall-supported bodyweight single-leg hinge; no band or anchor; YouTube channel metadata identifies Movement Library-StrengthHouse.') }),
  make({ id: 'upper-curl-band', name: 'Band biceps curl', category: 'arms', movementPattern: 'arms', setup: bandSetup('stand on the midpoint with feet hip-width and hold the opposite half in both hands, palms forward'), steps: ['Keep upper arms by the ribs and curl toward the shoulders.', 'Pause briefly without leaning back.', 'Lower until elbows are nearly straight while retaining mild tension.'], breathingTempo: 'Exhale on a 1–2-second curl; inhale on a 2–3-second lower.', primaryMuscles: ['biceps brachii'], secondaryMuscles: ['brachialis', 'brachioradialis', 'grip'], formCues: ['Elbows pinned', 'wrists neutral', 'shoulders quiet', 'curl not heave', 'slow lower'], commonMistakes: ['Leaning back', 'elbows drifting', 'snapping straight', 'band slack'], easierVariations: ['Lighter band', 'staggered stance', 'one arm'], harderVariations: ['Wider stance', 'shorter grip', '2-second squeeze'], bandWarnings, compatibleSubstitutionCategories: ['arms', 'pull-horizontal'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('H65_l__adPs', 'Fast Bicep Building Resistance Band Workout — Close Grip Curl', 'Fit Gent', '41-inch-loop-no-anchor', 'Visual frame at 0:10 shows a two-hand curl with a loop under both feet and no anchor.', 'https://www.youtube.com/watch?v=H65_l__adPs&t=8s') }),
  make({ id: 'lower-calf-raise', name: 'Standing calf raise', category: 'calves', movementPattern: 'calves', setup: bodySetup('Stand near a wall or chair with feet hip-width and toes forward; bodyweight is the V1 load.'), steps: ['Press through the base of the big toe and rise as high as balance permits.', 'Pause at the top without bouncing.', 'Lower slowly until heels touch.'], breathingTempo: 'Exhale on a 1–2-second rise; inhale on a 2–3-second lower.', primaryMuscles: ['gastrocnemius', 'soleus'], secondaryMuscles: ['foot and ankle stabilizers'], formCues: ['Tripod foot', 'rise straight up', 'heels track behind toes', 'quiet support hand', 'slow lower'], commonMistakes: ['Rolling outward', 'bending into a squat', 'bouncing', 'unstable furniture'], easierVariations: ['Two-hand support', 'smaller range'], harderVariations: ['Single-leg supported raise', 'longer pause'], bandWarnings: ['No loop is needed for V1.', 'Stop for calf or Achilles pain.', 'Use stable support.'], compatibleSubstitutionCategories: ['calves', 'squat'], defaultTarget: { kind: 'reps', min: 10, max: 15 }, media: video('MW2WG5l-fYE', 'Standing Heel Raises', 'Coury & Buehler Physical Therapy', 'bodyweight-no-anchor', 'Physical-therapy demonstration matches the bodyweight standing raise.') }),
  make({ id: 'core-bird-dog', name: 'Bird dog', category: 'core', movementPattern: 'core', setup: bodySetup('Start on hands and knees with hands under shoulders and knees under hips; use a mat.'), steps: ['Brace and extend one arm and opposite leg without arching or rotating.', 'Hold briefly, then return quietly.', 'Alternate sides with the tabletop still.'], breathingTempo: 'Exhale into the reach; inhale on return with a 2–3-second reach.', primaryMuscles: ['trunk stabilizers', 'multifidi'], secondaryMuscles: ['glutes', 'shoulders', 'hamstrings'], formCues: ['Tabletop still', 'reach long', 'hips square', 'toes point down', 'quiet return'], commonMistakes: ['Low-back arch', 'hip opening', 'shrugging', 'moving too fast'], easierVariations: ['Arm-only', 'leg-only', 'toe/hand taps'], harderVariations: ['Longer hold', 'slow return', 'light opposite-limb loop only after control'], bandWarnings: ['No band is required.', 'Do not add a band while balance is poor.', 'Stop for wrist, shoulder, or back pain.'], compatibleSubstitutionCategories: ['core'], defaultTarget: { kind: 'reps', min: 6, max: 10, perSide: true }, media: video('LaLKNS7mxrk', 'Bird Dog Exercise for Beginners', 'Margaret Martin, Physical Therapist', 'bodyweight-no-anchor', 'Physical-therapy quadruped demonstration exactly matches V1; YouTube channel metadata identifies Margaret Martin, Physical Therapist.') }),
  make({ id: 'reset-march', name: 'Marching in place', category: 'warmup', movementPattern: 'warmup', setup: bodySetup('Stand tall on a clear floor; use a counter if balance is uncertain.'), steps: ['Alternate lifting feet a few inches.', 'Swing arms naturally and land softly.', 'Keep the range conversational and low-impact.'], breathingTempo: 'Easy conversational breathing for 45–60 seconds.', primaryMuscles: ['hip flexors', 'calves'], secondaryMuscles: ['shoulders', 'trunk'], formCues: ['Tall posture', 'soft landing', 'opposite arm/leg', 'eyes forward', 'quiet feet'], commonMistakes: ['Holding breath', 'leaning back', 'stomping', 'lifting knees too high'], easierVariations: ['Seated march', 'toe taps'], harderVariations: ['Gentle cadence increase', 'larger arm swing'], bandWarnings: ['No band is used.', 'Stop for dizziness or balance loss.', 'Keep furniture out of the travel path.'], compatibleSubstitutionCategories: ['warmup', 'desk-reset'], defaultTarget: { kind: 'seconds', min: 45, max: 60 }, media: video('e_uIJdhwnj4', 'Marching in Place', 'Margaret Martin, Physical Therapist', 'bodyweight-no-anchor', 'Clinical low-impact marching demonstration matches the reset item; YouTube channel metadata identifies Margaret Martin, Physical Therapist.') }),
  make({ id: 'reset-thoracic-rotation', name: 'Thoracic rotation / book opener', category: 'mobility', movementPattern: 'mobility', setup: bodySetup('Lie on one side with knees bent and arms together in front, or use a comfortable seated variation.'), steps: ['Keep knees stacked and rotate the top arm and chest open.', 'Follow the hand with the eyes without forcing the neck.', 'Return slowly and repeat on the other side.'], breathingTempo: 'Inhale to open; exhale on return for 30–45 seconds per side.', primaryMuscles: ['thoracic rotators'], secondaryMuscles: ['pectoral muscles', 'posterior shoulder'], formCues: ['Knees stay stacked', 'move from upper back', 'neck follows gently', 'range stays comfortable', 'slow return'], commonMistakes: ['Knees separating', 'forcing the shoulder down', 'twisting from low back', 'holding breath'], easierVariations: ['Seated rotation', 'smaller arc'], harderVariations: ['Longer pause', 'reach farther only without lumbar rotation'], bandWarnings: ['No band is used.', 'Stop for sharp shoulder or back pain.', 'Stay within a pain-free range.'], compatibleSubstitutionCategories: ['mobility', 'desk-reset'], defaultTarget: { kind: 'seconds', min: 30, max: 45, perSide: true }, media: video('uzpyRbwYgGA', 'Thoracic Rotation / Book Opener', 'Physio REHAB', 'bodyweight-no-anchor', 'Physiotherapy mobility demonstration matches the no-equipment reset.') }),
  make({ id: 'reset-hip-flexor-stretch', name: 'Half-kneeling hip-flexor stretch', category: 'mobility', movementPattern: 'mobility', setup: bodySetup('Kneel with one knee down and the other foot forward; pad the knee and hold support if needed.'), steps: ['Tuck the pelvis gently and stack ribs over pelvis.', 'Shift forward a few inches without arching.', 'Breathe, then switch sides.'], breathingTempo: 'Slow nasal breathing for 30–45 seconds per side.', primaryMuscles: ['hip flexors'], secondaryMuscles: ['quadriceps', 'gluteus maximus'], formCues: ['Pelvis tucked', 'ribs stacked', 'front foot flat', 'glute gently active', 'small shift'], commonMistakes: ['Overarching', 'front knee collapsing', 'forcing range', 'holding breath'], easierVariations: ['Standing split stance', 'cushioned kneel'], harderVariations: ['Reach same-side arm overhead', 'longer hold'], bandWarnings: ['No band is used.', 'Stop for knee, hip, or back pain.', 'Do not bounce into the stretch.'], compatibleSubstitutionCategories: ['mobility', 'desk-reset'], defaultTarget: { kind: 'seconds', min: 30, max: 45, perSide: true }, media: video('UW1RAPG2-Yc', 'Hip Flexor Stretch -- the Psoas', 'Simon Brocard', 'bodyweight-no-anchor', 'Visual recheck on 2026-08-16 matches the no-equipment half-kneeling hip-flexor setup; YouTube channel metadata identifies Simon Brocard.') }),
  make({ id: 'reset-scapular-setting', name: 'Shoulder-blade retractions', category: 'postural-control', movementPattern: 'postural-control', setup: bodySetup('Stand or sit tall with arms relaxed and neck neutral; no band.'), steps: ['Gently draw shoulder blades down and together without flaring ribs.', 'Hold briefly without shrugging.', 'Release fully and repeat.'], breathingTempo: 'Exhale into the gentle set; inhale on release for 8–12 slow reps.', primaryMuscles: ['middle trapezius', 'rhomboids'], secondaryMuscles: ['lower trapezius', 'rotator cuff'], formCues: ['Neck long', 'ribs down', 'shoulders away from ears', 'small movement', 'relaxed hands'], commonMistakes: ['Shrugging', 'arching', 'forcing blades together', 'holding breath'], easierVariations: ['Seated version', 'smaller range'], harderVariations: ['Longer hold', 'wall slide without pain'], bandWarnings: ['No band is used.', 'Stop for shoulder pain or tingling.', 'This is posture practice, not a maximal squeeze.'], compatibleSubstitutionCategories: ['postural-control', 'pull-apart'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('sPSOQ7RwpgQ', 'Shoulder Blade Setting', 'Cornell Health', 'bodyweight-no-anchor', 'Clinical postural-control demonstration matches the no-equipment reset.') }),
  make({ id: 'reset-bodyweight-squat', name: 'Bodyweight squat', category: 'desk-reset', movementPattern: 'desk-reset', setup: bodySetup('Stand with feet about shoulder-width and use a chair as a depth target if helpful.'), steps: ['Sit hips down and back while knees follow toes.', 'Descend to a comfortable depth with heels planted.', 'Stand by pushing the floor away.'], breathingTempo: 'Inhale down for 2 seconds; exhale to stand for 1–2 seconds.', primaryMuscles: ['quadriceps', 'gluteus maximus'], secondaryMuscles: ['hamstrings', 'adductors', 'trunk'], formCues: ['Tripod feet', 'knees follow toes', 'chest relaxed', 'heels stay down', 'smooth tempo'], commonMistakes: ['Knees cave', 'heels lift', 'depth forced', 'rushing'], easierVariations: ['Chair squat', 'partial range'], harderVariations: ['Pause', 'slower eccentric'], bandWarnings: ['No band is used in the reset.', 'Stop for pain or dizziness.', 'Keep the reset comfortable, not fatiguing.'], compatibleSubstitutionCategories: ['desk-reset', 'squat'], defaultTarget: { kind: 'reps', min: 8, max: 12 }, media: video('r0kHBKP02y0', 'Bodyweight Squat', 'Keep It Moving Physical Therapy', 'bodyweight-no-anchor', 'Physical-therapy movement-break demonstration matches the no-equipment squat; YouTube channel metadata identifies Keep It Moving Physical Therapy.') }),
]

export const exerciseById: Readonly<Record<string, Exercise>> = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise]))

export const workoutExerciseIds = exercises.filter((exercise) => exercise.movementPattern !== 'desk-reset' && !exercise.id.startsWith('reset-')).map((exercise) => exercise.id)

export const mediaSources = exercises.map((exercise) => exercise.media)

/** A production catalog may expose only media that has passed the release check. */
export const isProductionMedia = (media: ExerciseMedia): boolean => media.equipmentFit !== 'needs-replacement'

export const productionMedia = mediaSources.filter(isProductionMedia)

export const hasOnlyProductionMedia = (): boolean => exercises.every((exercise) => isProductionMedia(exercise.media))

export const movementPatterns = exercises.reduce<MovementPattern[]>((patterns, exercise) => patterns.includes(exercise.movementPattern) ? patterns : [...patterns, exercise.movementPattern], [])

export const targets: Readonly<Record<string, Target>> = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise.defaultTarget]))

export const exerciseCatalog = exercises
